### ISSUE TITLE
Event API (not really an issue)

### ISSUE THREAD

**Issue by oKcerG** [samvdb/php-musiccast-api#1]
Hello, 
First and foremost, this is not an issue with your lib, more of a question about the implementation.
I'm trying to implement something similar in c++ but I can't seem to receive UDP events.

I send the correct headers, `X-AppName` and `X-AppPort`, bind to the port with a UDP socket, but I never get packets. 

Does it work with your library?
Is there any gotchas?

Cheers.

**Comment by samvdb** [comment]
Hi @oKcerG ,

Please make sure you send MusicCast and version 1 as the headers, it works if you do it like that.
Could you sniff your network traffic to make sure the unicasts are actually sent out?

Edit:
I use this library myself with the following arguments:
$api->subscribe(41100, 'MusicCast', '1.40(iOS)');

Not sure why i used 1.40(iOS)... Could be related :)

**Comment by oKcerG** [comment]
Thanks @samvdb, that was it.
It appears that the `X-AppName` header has to be of the form `MusicCast/.+` (case insensitive).

**Comment by samvdb** [comment]
Glad to be of help!
Good luck
