### ISSUE TITLE
Event Subscription

### ISSUE THREAD

**Issue by TCURT15** [samvdb/php-musiccast-api#2]
I get the following error when trying to subscribe to events. 

`Fatal error: Uncaught MusicCast\Exception\ErrorException: Invalid Request (A method did not exist, a method wasn’t appropriate etc.) in /var/www/html/remote/vendor/samvdb/php-musiccast-api/lib/MusicCast/HttpClient/Plugin/MusicCastExceptionThrower.php:28 Stack trace: #0 /var/www/html/remote/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(34): MusicCast\HttpClient\Plugin\MusicCastExceptionThrower->MusicCast\HttpClient\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response)) #1 /var/www/html/remote/vendor/samvdb/php-musiccast-api/lib/MusicCast/HttpClient/Plugin/MusicCastExceptionThrower.php(37): Http\Client\Promise\HttpFulfilledPromise->then(Object(Closure)) #2 /var/www/html/remote/vendor/php-http/client-common/src/PluginClient.php(160): MusicCast\HttpClient\Plugin\MusicCastExceptionThrower->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure)) #3 /var/www/html/remote/vendor/php-http/client-common/src/PluginClient.php(174): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Obje in /var/www/html/remote/vendor/samvdb/php-musiccast-api/lib/MusicCast/HttpClient/Plugin/MusicCastExceptionThrower.php on line 28`

**Comment by samvdb** [comment]
Hi,

Could you provide more info about the request?
What method are you calling? What version is your musiccast running on?

**Comment by mistljo** [comment]
got the same error->I call $musiccast->api('events')->subscribe()
